# This is a basic workflow to help you get started with Actions

name: terraform workflow

on:
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      ARM_CLIENT_ID: ${{secrets.AZURE_AD_CLIENT_ID}}
      ARM_CLIENT_SECRET: ${{secrets.AZURE_AD_SECRET}}
      ARM_SUBSCRIPTION_ID: ${{secrets.AZURE_AD_SUBSCRIPTION_ID}}
      ARM_TENANT_ID: ${{secrets.AZURE_AD_TENANT_ID}}
    environment: dev
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
    
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
            terraform_version: 
    
      - name: Terraform Init
        run: terraform init
    
      - name: Terraform Plan
        run: terraform plan -out=tfplan
    
      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
         
       
    
