# This is a basic workflow to help you get started with Actions

name: terraform workflow

on:
  workflow_dispatch:
    inputs:
      command:
        description: 'Select Terraform Action'
        required: true
        default: 'plan'
        type: choice
        options:
          - plan
          - apply
          - destroy-dryrun
          - destroy
      resource:
        description: 'Select the resource'
        required: true
        default: 'virtual_network'
        type: choice
        options:
          - virtual_network
          - storage_account
          - AKS_CLUSTER

jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      AZ_CLIENT_ID: ${{secrets.AZ_CLIENT_ID}}
      AZ_SECRET_ID: ${{secrets.AZ_SECRET_ID}}
      AZ_TENANT_ID: ${{secrets.AZ_TENANT_ID}}
      AZ_SUBSCRIPTION_ID: ${{secrets.AZ_SUBSCRIPTION_ID}}
    defaults:
      run:
        shell: bash
        working-directory: ./resource
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
    
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
            terraform_version:
    
      - name: Terraform Init
        id: init
        run: |
          echo "Change Directory"
          cd ${{ github.event.inputs.resource }}
          terraform init 
    
      - name: Terraform Plan
        id: plan
        if: github.event.inputs.command == 'plan'
        run: |
          echo "Change Directory"
          cd ${{ github.event.inputs.resource }}
          terraform plan -out=tfplan
        continue-on-error: false        
    
      - name: Terraform Apply
        id: apply
        if: github.event.inputs.command == 'apply'
        run: |
          echo "Change Directory"
          cd ${{ github.event.inputs.resource }}
          terraform plan -input=false
          sleep 10
          terraform apply -auto-approve
        continue-on-error: false

      - name: Terraform Destroy Dryrun
        id: destroy-dryrun
        if: github.event.inputs.command == 'destroy-dryrun'
        run: |
          echo "Change Directory"
          cd ${{ github.event.inputs.resource }}
          terraform plan -destroy -out=tfplan
        continue-on-error: false

      - name: Terraform destroy
        id: destroy
        if: github.event.inputs.command == 'destroy'
        run: |
          echo "Change Directory"
          cd ${{ github.event.inputs.resource }}
          terraform destroy -auto-approve
        continue-on-error: false
        
       
    
