# This is a basic workflow to help you get started with Actions

name: terraform workflow

on:
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      ARM_CLIENT_ID: ${{secrets.AZURE_AD_CLIENT_ID}}
      ARM_CLIENT_SECRET: ${{secrets.AZURE_AD_SECRET}}
      ARM_SUBSCRIPTION_ID: ${{secrets.AZURE_AD_SUBSCRIPTION_ID}}
      ARM_TENANT_ID: ${{secrets.AZURE_AD_TENANT_ID}}
    environment: dev
    defaults:
      run:
        shell: bash
    steps:
      - name: Get code
        uses: actions/checkout@v3

      - name: 'Terraform Format'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 3.92.0
          tf_actions_subcommand: 'fmt'
          

      - name: 'Terraform init'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 3.92.0
          tf_actions_subcommand: 'init'
          

      - name: 'Terraform validate'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 3.92.0
          tf_actions_subcommand: 'validate'
          

      - name: 'Terraform plan'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 3.92.0
          tf_actions_subcommand: 'plan'
          

      - name: 'Terraform apply'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 3.92.0
          tf_actions_subcommand: 'apply'
          

         
       
    
